apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build-and-deploy-pr
  namespace: hict-ngw-dev
spec:
  params:
    - default: spring-petclinic
      name: IMAGE_NAME
      type: string
    - default: >-
        http://do-gitlab-ce.apps.apps.dev.honecloud.co.kr/root/spring-petclinic-ngw.git
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: maven-build
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven-build
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: ARGS
          value:
            - oc start-build spring-petclinic --from-dir /tmp/src
      runAfter:
        - maven-build
      taskRef:
        kind: Task
        name: openshift-cli-workspaces
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
